### ISSUE TITLE
PR올리려면 develop 브랜치에 올리는거 맞나요?

### ISSUE THREAD

**Issue by darron1217** [akasima/xero_commerce#123]
지금은 develop 브랜치가 master 브랜치보다 20 커밋이나 밀려있어서 괜찮을지 모르겠네요^^;

**Comment by akasima** [comment]
네네 develop 으로 . 오늘부터 따라 잡겠습니다.

**Comment by darron1217** [comment]
드디어 오셨군요..ㅠ
감사합니다

**Comment by akasima** [comment]
브랜치 관리를.. 제가 똥꾸녕으로 했네요 ;; 왜 마스터에 커밋이 더 많은지..
master -> develop merge 하고 양쪽에서 설치 테스트 진행하고..
다시 mater pr merge 하고 
master -> develop merge 하고 

store 에 배포 한번 하고..

따라 잡을게요.

**Comment by akasima** [comment]
제가.. master 로 들어온 pr을 merge 했네요 ;;

**Comment by darron1217** [comment]
아 제가 develop으로 그냥 했어야 했는데...
꼬여버렸네요
