### ISSUE TITLE
적극적으로 기여하고 싶은데, Slack같은 채널을 여실 생각은 없으신지요?

### ISSUE THREAD

**Issue by darron1217** [akasima/xero_commerce#129]
제곧내 입니다

당분간은 쇼핑몰 개발에 매진할 계획이라 기여를 많이 하고싶은데, 소통이 원활하지 않으면 제가 혼자 이상한 방향으로 가버릴것 같아서요ㅎ

보다 밀접한 소통채널이 생겼으면 좋겠습니다 :)

**Comment by akasima** [comment]
XE 포럼 에 들어와 있으세요?
Share 제로커머스 outside of XE Forum 을 만들었습니다. 지금 막!

**Comment by darron1217** [comment]
네네 포럼에는 항상 상주하고 있긴 합니다
채팅형식은 아니어서 조금 대화하기 불편한 감은 있네요

**Comment by akasima** [comment]
아. 슬랙이요.
슬랙에 있지 않으셨나요?

**Comment by darron1217** [comment]
아 그렇네요
활동량이 적어서 까먹고 있었네요ㅎㅎ

**Comment by darron1217** [comment]
슬랙을 써도 별로 활동적이지는 않을것 같네요
일단 홈페이지에 있는 포럼 적극 활용해 보겠습니다
