### ISSUE TITLE
상품 등록할 때 javascript 폼 체크

### ISSUE THREAD

**Issue by akasima** [akasima/xero_commerce#32]
상품 등록할 때 php 에서 validation 처리되어 입력하던 이미지 정보, 태그 정보가 사라지는 문제가 있습니다.
되도록 javascript 에서 폼 체크 해서 이미지, 태그 정보가 사라지지 않도록 개선되었으면 좋겠습니다.

**Comment by kimyu711** [comment]
submit 보내기전에 validation이 되어 정보가 사라지지 않는 것으로 확인되어 close합니다.
