### ISSUE TITLE
사이트 매뉴 편집에서 상품 목록 카테고리가 수정되지 않는 문제

### ISSUE THREAD

**Issue by akasima** [akasima/xero_commerce#33]
메뉴에서 수정할 때 리스트에 표시할 카테고리를 선택해서 설정이 적용되지 않습니다.

**Comment by kimyu711** [comment]
상품목록카테고리를 선택하고 수정하면 적용되는 카테고리군은 변경되어 나타나지만 페이지 이름이 변경되지 않아 설정이 적용되지 되지 않은 것처럼 보이는 것 같습니다. 카테고리가 변경되었을 때 자동으로 페이지 이름을 변경해주던지, 페이지이름과 카테고리가 맞는지 확인하는 alert이 필요할 것 같은데 어떤 부분이 나을지 고민이 필요할 것 같습니다.
