### ISSUE TITLE
사용자 사이트 > 주문자 정보 입력

### ISSUE THREAD

**Issue by akasima** [akasima/xero_commerce#39]
사용자 사이트에서 결제 시도할 때 주문자 정보 입력 페이지 개선

- [x] 이름, 전화번호 입력하지 않은 경우 javascript form check (지금은 다음 페이지에서 오류 발생)
- [x] 약관 개선 ( 수집하는 정보에 대한 표준 약관 제공)
- [x] 실명인증 필요한지 법적인 이슈 확인 필요
- [x] 결제 관리에 설정이 되지 않은 경우 경고창 출력 필요 (전체 화면을 가리는 모달 창 , '결제 방식 설정에 문제가 있습니다. 관리자에게 문의 바랍니다')

**Comment by kimyu711** [comment]
https://echosting.cafe24.com/Cs/?url=CsView&type=notice&no=279346
해당 조항에 따라 실명인증은 필수요소가 아님
