### ISSUE TITLE
상품등록할 때 이미지 등록 처리 문제

### ISSUE THREAD

**Issue by akasima** [akasima/xero_commerce#44]
사진 업로드에 이미지를 첨부하고 

에디터 영역에서 내용 작성을 위해 이미지를 첨부하면 사진 업로드 부분의 이미지가 변경되는 문제 
> 등록은 정상적으로 되지만 미리보기 이미지가 변경되는 문제

**Comment by kimyu711** [comment]
https://github.com/xpressengine/xpressengine/commit/b5496e69ff2ca358a4f69adca34cdb5494f62ead 에서 해결
