### ISSUE TITLE
상품 등록할 때 기본 옵션이 등록되지 않는 문제

### ISSUE THREAD

**Issue by akasima** [akasima/xero_commerce#46]
상품 등록 후 기본 옵션이 존재하지 않음

**Comment by kimyu711** [comment]
정상적으로 등록이 되었다면 기본옵션이 존재하는데...mmfootshop과 같은 버전임에도 기본옵션이 안생기는 현상 재현이 안되고 있습니다ㅠㅠ등록시에 특별한 조건이 있었는지 확인이 필요할 것 같습니다.

**Comment by kimyu711** [comment]
재현시에 재등록.
