### ISSUE TITLE
사용자 페이지 sns 공유하기 기능 오류

### ISSUE THREAD

**Issue by akasima** [akasima/xero_commerce#49]
sns 기능 공유할 때 동작 안하는 문제

**Comment by kimyu711** [comment]
페이스북에서는 sns기능을 통한 링크 또는 이미지 공유가 가능하지만, 인스타그램은 웹상에서 sns기능을 통한 링크, 이미지 공유를 지원하고 있지 않는 것으로 확인됩니다.
https://www.instagram.com/developer/
https://stackoverflow.com/questions/17673156/instagram-share-photo-from-webpage
https://www.quora.com/How-do-I-share-a-link-on-Instagram
다른 sns (트위터)를 대체하는 법으로 생각해보아야할 것 같습니다.

**Comment by kimyu711** [comment]
카카오톡 공유하기 기능 참조할 것

**Comment by kimyu711** [comment]
https://devtalk.kakao.com/t/v1/42538/3
https://imweb.me/faq?mode=view&category=30&category2=50&idx=36463
api키 등록 없이는 카카오톡공유하기는 사용하기 힘들 것으로 보입니다.
현재 게시판에 있는 페이스북과 라인으로 사용하고, 추후 커머스 sns플러그인을 추가할 수 있게하는 방향으로 더해갈 수 있게 하겠습니다

**Comment by kimyu711** [comment]
https://github.com/akasima/xero_commerce/commit/389e76ee6caad69c14ee4a018c01d6ab2b2bc78b
