### ISSUE TITLE
Debug 모드에서 발생하는 오류

### ISSUE THREAD

**Issue by smaker** [akasima/xero_commerce#67]
### 오류 ###

`Undefined` offset: 0 (View: /home/***/***/plugins/xero_commerce/views/setting/product/create.blade.php)`

[상품관리] > [상품 등록]

위 메뉴 접근 시, 위와 같은 오류가 발생합니다.

**Comment by kimyu711** [comment]
상품 등록을 하려면 해당아이디가 쇼핑몰을 관리할 수 있어야 하는데
관리자아이디가 쇼핑몰을 관리할 수 있는 권한을 가지지 못해서 일어난 오류로 파악되었습니다.
설치시 기본으로 쇼핑몰관리자로 등록하고 폼 검증을 할 수 있도록 개선하겠습니다.

그 전까지는 환경설정의 입점몰 설정에 가셔서 미리 생성되어있는 입점몰을 수정하신 후 관리자 아이디에 해당 아이디를 등록시켜주시면 상품등록 페이지가 나타날것으로 보입니다.

**Comment by smaker** [comment]
@kimyu711 감사합니다. 알려주신 대로 하니까 정상적으로 나오네요.
