### ISSUE TITLE
인스톨시에 서버에서 jpeg 지원하는지 체크

### ISSUE THREAD

**Issue by kimyu711** [akasima/xero_commerce#69]

**Comment by akasima** [comment]
@kimyu711 jpeg 를 지원하지 않으면 어디서 문제가 발생하나요?

**Comment by kimyu711** [comment]
설치과정에서 샘플 상품페이지에 이미지를 저장하지 못해서 도중에 에러가 나고 맙니다. 이는 XE코어에서 이미지 업로드 및 저장문제와도 직결이 되고 있어 코어와 함께 수정작업할 예정입니다. (보통의 호스팅서버에서는 jpeg 이미지업로드 지원이 되고 있어 문제가 없지만 서버설정문제이기 때문에 체크후에 에러안내메세지를 띄울 계획입니다.)
