### ISSUE TITLE
상품 등록 개선

### ISSUE THREAD

**Issue by akasima** [akasima/xero_commerce#73]
- [x] 상품 등록할 때 필수 입력 정보가 숨겨져 있어 불편함
- [x] 기본 배송정보를 설정할 수 있도록 하고 설정한 배송방법이 선택되어 있도록 수정
- [ ] 한번에 여러장 사진을 등록할 수 있도로 개선
- [x] 판매 가격에 세자리 마다 콤마 처리
- [x] 주요 정보 순서로 입력할 수 있도록 입력 순서 개선

**Comment by kimyu711** [comment]
https://github.com/akasima/xero_commerce/commit/fbd6dcff96efb009088ae00eebe9034d406a7b33
