### ISSUE TITLE
대표사진이 썸네일 처리되지 않는 문제

### ISSUE THREAD

**Issue by akasima** [akasima/xero_commerce#80]
큰 이미지 파일을 올렸는데. 그 사진이 그대로 사용되는 문제

**Comment by kimyu711** [comment]
체크해보니 어느부분이 썸네일처리없이 그냥 사용되었는지 확인을 할 수 없었습니다. (체크 부분 - 상품 상세페이지, 메인 위젯페이지, 상품카테고리페이지, 관리자 상품리스트 페이지) 다만 썸네일이 기존에 요구하는 사이즈보다 큼직하게 나오는 부분들을 찾아 적절한 사이즈를 로드하도록 일부 로드하는 사이즈를 수정했습니다.
