### ISSUE TITLE
쇼핑몰 로고 파일(svg) 등록 시 에러가 발생합니다.

### ISSUE THREAD

**Issue by smaker** [akasima/xero_commerce#81]
### 재현 방법
쇼핑몰 로고를 svg 파일로 업로드 합니다.
(png 파일은 정상적으로 업로드 됩니다.)

### 에러 내용

Intervention\Image\Exception\NotReadableException thrown with message "Unable to read image from file (/tmp/phpDpyIjV)."

Stacktrace:
#82 Intervention\Image\Exception\NotReadableException in /home/simplesoft/public_html/vendor/intervention/image/src/Intervention/Image/Gd/Decoder.php:21
#81 Intervention\Image\Gd\Decoder:initFromPath in /home/simplesoft/public_html/vendor/intervention/image/src/Intervention/Image/AbstractDecoder.php:285
#80 Intervention\Image\AbstractDecoder:init in /home/simplesoft/public_html/vendor/intervention/image/src/Intervention/Image/AbstractDriver.php:64
#79 Intervention\Image\AbstractDriver:init in /home/simplesoft/public_html/vendor/intervention/image/src/Intervention/Image/ImageManager.php:50
#78 Intervention\Image\ImageManager:make in /home/simplesoft/public_html/plugins/xero_commerce/src/Handlers/XeroCommerceImageHandler.php:31
#77 Xpressengine\Plugins\XeroCommerce\Handlers\XeroCommerceImageHandler:resize in /home/simplesoft/public_html/plugins/xero_commerce/src/Handlers/XeroCommerceImageHandler.php:22
#76 Xpressengine\Plugins\XeroCommerce\Handlers\XeroCommerceImageHandler:resizeAfterSave in /home/simplesoft/public_html/plugins/xero_commerce/src/Controllers/Settings/ShopConfigController.php:37
#75 Xpressengine\Plugins\XeroCommerce\Controllers\Settings\ShopConfigController:store in /home/simplesoft/public_html/vendor/laravel/framework/src/Illuminate/Routing/Controller.php:54
#74 call_user_func_array in /home/simplesoft/public_html/vendor/laravel/framework/src/Illuminate/Routing/Controller.php:54
#73 Illuminate\Routing\Controller:callAction in /home/simplesoft/public_html/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php:45
#72 Illuminate\Routing\ControllerDispatcher:dispatch in /home/simplesoft/public_html/vendor/laravel/framework/src/Illuminate/Routing/Route.php:212
#71 Illuminate\Routing\Route:runController in /home/simplesoft/public_html/vendor/laravel/framework/src/Illuminate/Routing/Route.php:169
#70 Illuminate\Routing\Route:run in /home/simplesoft/public_html/vendor/laravel/framework/src/Illuminate/Routing/Router.php:658
#69 Illuminate\Routing\Router:Illuminate\Routing\{closure} in /home/simplesoft/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:30
#68 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /home/simplesoft/public_html/core/src/Xpressengine/Settings/SettingsMiddleware.php:83
#67 Xpressengine\Settings\SettingsMiddleware:handle in /home/simplesoft/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
#66 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /home/simplesoft/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#65 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /home/simplesoft/public_html/app/Http/Middleware/AsyncExpose.php:41
#64 App\Http\Middleware\AsyncExpose:handle in /home/simplesoft/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
#63 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /home/simplesoft/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#62 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /home/simplesoft/public_html/app/Http/Middleware/FreezeSEO.php:42
#61 App\Http\Middleware\FreezeSEO:handle in /home/simplesoft/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
#60 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /home/simplesoft/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#59 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /home/simplesoft/public_html/app/Http/Middleware/Purifying.php:46
#58 App\Http\Middleware\Purifying:handle in /home/simplesoft/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
#57 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /home/simplesoft/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#56 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /home/simplesoft/public_html/app/Http/Middleware/LangPreprocessor.php:79
#55 App\Http\Middleware\LangPreprocessor:handle in /home/simplesoft/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
#54 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /home/simplesoft/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#53 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /home/simplesoft/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php:68
#52 Illuminate\Foundation\Http\Middleware\VerifyCsrfToken:handle in /home/simplesoft/public_html/app/Http/Middleware/ExceptAppendableVerifyCsrfToken.php:49
#51 App\Http\Middleware\ExceptAppendableVerifyCsrfToken:handle in /home/simplesoft/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
#50 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /home/simplesoft/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#49 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /home/simplesoft/public_html/app/Http/Middleware/RequiredDF.php:69
#48 App\Http\Middleware\RequiredDF:handle in /home/simplesoft/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
#47 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /home/simplesoft/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#46 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /home/simplesoft/public_html/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php:41
#45 Illuminate\Routing\Middleware\SubstituteBindings:handle in /home/simplesoft/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
#44 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /home/simplesoft/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#43 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /home/simplesoft/public_html/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php:49
#42 Illuminate\View\Middleware\ShareErrorsFromSession:handle in /home/simplesoft/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
#41 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /home/simplesoft/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#40 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /home/simplesoft/public_html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php:63
#39 Illuminate\Session\Middleware\StartSession:handle in /home/simplesoft/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
#38 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /home/simplesoft/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#37 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /home/simplesoft/public_html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php:37
#36 Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse:handle in /home/simplesoft/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
#35 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /home/simplesoft/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#34 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /home/simplesoft/public_html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php:66
#33 Illuminate\Cookie\Middleware\EncryptCookies:handle in /home/simplesoft/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
#32 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /home/simplesoft/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#31 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /home/simplesoft/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:102
#30 Illuminate\Pipeline\Pipeline:then in /home/simplesoft/public_html/vendor/laravel/framework/src/Illuminate/Routing/Router.php:660
#29 Illuminate\Routing\Router:runRouteWithinStack in /home/simplesoft/public_html/vendor/laravel/framework/src/Illuminate/Routing/Router.php:635
#28 Illuminate\Routing\Router:runRoute in /home/simplesoft/public_html/vendor/laravel/framework/src/Illuminate/Routing/Router.php:601
#27 Illuminate\Routing\Router:dispatchToRoute in /home/simplesoft/public_html/vendor/laravel/framework/src/Illuminate/Routing/Router.php:590
#26 Illuminate\Routing\Router:dispatch in /home/simplesoft/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:176
#25 Illuminate\Foundation\Http\Kernel:Illuminate\Foundation\Http\{closure} in /home/simplesoft/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:30
#24 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /home/simplesoft/public_html/plugins/freezer/src/Middlewares/Middleware.php:59
#23 Xpressengine\Plugins\Freezer\Middlewares\Middleware:handle in /home/simplesoft/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
#22 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /home/simplesoft/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#21 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /home/simplesoft/public_html/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php:58
#20 Barryvdh\Debugbar\Middleware\InjectDebugbar:handle in /home/simplesoft/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
#19 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /home/simplesoft/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#18 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /home/simplesoft/public_html/vendor/fideloper/proxy/src/TrustProxies.php:56
#17 Fideloper\Proxy\TrustProxies:handle in /home/simplesoft/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
#16 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /home/simplesoft/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#15 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /home/simplesoft/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php:30
#14 Illuminate\Foundation\Http\Middleware\TransformsRequest:handle in /home/simplesoft/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
#13 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /home/simplesoft/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#12 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /home/simplesoft/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php:30
#11 Illuminate\Foundation\Http\Middleware\TransformsRequest:handle in /home/simplesoft/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
#10 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /home/simplesoft/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#9 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /home/simplesoft/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php:27
#8 Illuminate\Foundation\Http\Middleware\ValidatePostSize:handle in /home/simplesoft/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
#7 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /home/simplesoft/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#6 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /home/simplesoft/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php:46
#5 Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode:handle in /home/simplesoft/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
#4 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /home/simplesoft/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#3 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /home/simplesoft/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:102
#2 Illuminate\Pipeline\Pipeline:then in /home/simplesoft/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:151
#1 Illuminate\Foundation\Http\Kernel:sendRequestThroughRouter in /home/simplesoft/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:116
#0 Illuminate\Foundation\Http\Kernel:handle in /home/simplesoft/public_html/index.php:57

**Comment by akasima** [comment]
감사합니다. 

사용하면서 오류 발생한거랑, 개선사항 의견 가득이 던져주세요..

**Comment by kimyu711** [comment]
해당 쇼핑몰을 설치한 서버가 svg 파일지원을 하지 않는 것 같습니다. shell 접속이 가능한 환경이시라면
sudo apt-get install librsvg2-dev 또는
sudo yum install librsvg2-devel 을 실행하여 svg를 지원하는 라이브러리를 설치해주세요.
호스팅환경이시라면 호스팅서비스사에 문의를 해보셔야 할 것 같습니다.

**Comment by smaker** [comment]
@kimyu711  `sudo apt-get install librsvg2-dev` 를 입력하여 라이브러리를 설치했으나 동일합니다.

![screenshot-simplesoft io-2019 04 05-14-23-29](https://user-images.githubusercontent.com/1732040/55605231-80e61880-57ae-11e9-8eec-c095d8f4f87e.png)

**Comment by kimyu711** [comment]
https://github.com/Intervention/image/issues/580

라라벨에서 사용하는 Intervention/GD 라이브러리가  SVG를 지원하지않아 일어난 문제였습니다. 우회적으로  svg를 가지고 새로 resize해서 png로 저장하는 법으로 업로드 받을 수 있도록 구현하겠습니다.
