### ISSUE TITLE
설치 불가능(composer 오류)

### ISSUE THREAD

**Issue by fromthere** [akasima/xero_commerce#87]
```
> Xpressengine\Plugin\Composer\Composer::command
xpressengine-installer: running in update mode
xpressengine-installer: Plugin composer file[storage/app/composer.plugins.json] is written
> Xpressengine\Plugin\Composer\Composer::preUpdateOrInstall
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

Problem 1
- Installation request for xpressengine-plugin/xero_commerce 1.0.0 -> satisfiable by xpressengine-plugin/xero_commerce[1.0.0].
- xpressengine-plugin/xero_commerce 1.0.0 requires xpressengine-plugin/banner 0.9.4 -> satisfiable by xpressengine-plugin/banner[0.9.4] but these conflict with your requirements or minimum-stability.
```

위 오류가 발생하며 설치되지 않습니다.

**Comment by Kazto-lsk** [comment]
사용하고 계시는 xe3의 설치 환경은 어떻게 되시나요?

1. ssh설치 / FTP업로드 설치
2. 코어의 버전

으로 전달 부탁드립니다.

**Comment by fromthere** [comment]
1. SSH로 설치했습니다.
2. 3.0.0으로 설치했다 diff 파일로 3.0.1 업로드후 artisan xe:update 했습니다.

**Comment by Kazto-lsk** [comment]
안녕하세요.
해당 문제를 확인하기 위해, 다소 시간이 걸릴 수 있습니다.
최대한 빠른 시간안에 확인 후 안내해드릴 수 있도록 하겠습니다.

XE, Xero-commerce를 선택해주셔서 감사합니다.

**Comment by Kazto-lsk** [comment]
안녕하세요, 해당 문제를 해결하기 위하여, nginx php 7.2 환경이 구성된 서버에서 말씀해주신 방법대로 업데이트 하였으나, 정상적으로 설치 되는것으로 확인됩니다.

혹시 xe가 설치된 문서 경로에 composer install을 해보셨는지 문의드립니다.

감사합니다.

**Comment by fromthere** [comment]
`composer update`는 실행한적 있지만 install은 해본적 없습니다. 해보고 댓글 달겠습니다.

**Comment by Kazto-lsk** [comment]
@fromthere 안녕하세요, 해당 문제에 대해서 해결이 되셨는지 후속 문의를 드립니다.
해결이 되셨다면, 이슈를 닫아주시면 감사하겠으며, 해결이 여전히 되지 않으셨다면 문제를 공유 부탁드리겠습니다.

감사합니다.

**Comment by kimyu711** [comment]
https://github.com/akasima/xero_commerce/issues/89
함께 처리 예정

**Comment by kimyu711** [comment]
https://github.com/akasima/xero_commerce/commit/c77aa742ea7ffd7d3127eebb85123a17c67c2f6c
