### ISSUE TITLE
XE 3.0.1 에서 설치 불가능

### ISSUE THREAD

**Issue by Kazto-lsk** [akasima/xero_commerce#89]
현재 배너 플러그인의 최신 버전(관리자 페이지에서 설치함)을 설치하고, 제로 커머스를 플러그인 설치를 통해서 설치하는데, 정상적으로 설치가 되지 않고 있습니다.
<img width="1646" alt="스크린샷 2019-04-05 오후 12 53 02" src="https://user-images.githubusercontent.com/47233861/55602706-e1bb2400-57a1-11e9-92b2-d3b5bed1c671.png">

**Comment by kimyu711** [comment]
https://github.com/akasima/xero_commerce/commit/c77aa742ea7ffd7d3127eebb85123a17c67c2f6c
